name: 'Deploy to AWS S3'
description: 'Deploy to AWS S3 bucket'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'node20'
  # pre: 'pre.js'
  main: 'index.js'
  # post: 'post.js'
