name: 'Deploy to AWS S3'
description: 'Deploy to AWS S3 bucket'
inputs:
  bucket:
    description: 'S3 bucket name'
    required: true
  bucket-region:
    description: 'S3 bucket-region name'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'Folder contains deploy files'
    required: true
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'node20'
  # pre: 'pre.js'
  main: 'main.js'
  # post: 'post.js'
