name: 'Deploy to AWS S3'
description: 'Deploy to AWS S3 bucket'
inputs:
  tag-name:
    description: "Name of tag to create on repo"
    required: true
  user-name:
    description: "Git user name"
    required: true
  user-email:
    description: "E-mail for git user"
    required: true
  token:
    description: "User token"
    required: true
  repo-path:
    description: "Relative path under to place the repository if not $GITHUB_WORKSPACE"
    required: false
    default: ''
outputs:
  new-tag:
    description: 'The url to website'
runs:
  using: 'docker'
  image: 'Dockerfile'
