name: 'Update Submodules and Tag'
description: 'A custom GitHub Action to update submodules, commit changes, create a tag, and push it to the repository'
inputs:
  token:
    description: 'GitHub token'
    required: true
  repo-url:
    description: 'Git repository URL'
    required: true
  branch:
    description: 'Branch to update and tag'
    required: true
  tag-name:
    description: 'Tag name'
    required: true
  tag-message:
    description: 'Tag message'
    required: false
  user-name:
    description: "Git user name"
    required: true
  user-email:
    description: "E-mail for git user"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
